package ServerApp;

import java.util.*;

import java.io.File;
import java.io.StringReader;

import org.dom4j.Document;
import org.dom4j.DocumentException;
//import org.dom4j.Element;
import org.dom4j.Node;
import org.dom4j.io.SAXReader;
/*
 * Class responsible for the parsing of the XML forms that are being generated by the Weather generator.
 */
public class Dom4jParser implements Runnable{
	private ServerApp serverApp;
	
	private String buffer; // buffer recieved from the weatherdataclient that contains the xml form
	private StationBufferMap stationBufferMap;
	
	// containers for the parsed xml
	private String stationnumber;
	private String date;
	private String time;
	private String temperature;
	private String dewpoint;
	private String airpresurestationlevel;
	private String airpresuresealevel;
	private String visability;
	private String windspeed;
	private String perception;
	private String snowfallen;
	private String specialcircumstances;
	private String cloudiness;
	private String winddirection;
	
	/*
	 * constructor for the parser
	 * @param buffer			the buffer recieved from the weatherDataClient
	 * @param serverapp 		the main application object that this object belongs to
	 * @param stationbuffermap 	the object that will contain the global buffer and a reference to the stationbuffer
	 */
	public Dom4jParser(ServerApp serverapp, String buffer, StationBufferMap stationBufferMap){
		this.serverApp = serverapp;
		this.buffer = buffer;
		this.stationBufferMap = stationBufferMap;
		
	}
	/*
	 * Starts the Parser thread
	 */
	public void run(){
		parse(this.buffer);
	}
	
	/*
	 * method for parsing the input from the weatherdata generator.
	 * @param buffer 	the buffer recieved from weatherdata client that needs to be parsed
	 */
	public void parse(String buffer) {

	      try {
	         SAXReader reader = new SAXReader();
	         Document document = reader.read(new StringReader(this.buffer)); // create a document from the input this.buffer

	         List<Node> nodes = document.selectNodes("/WEATHERDATA/MEASUREMENT" ); // add all /weatherdata/measurment nodes to the a list
	         	         
	         for (Node node : nodes) {
	                  
	            this.stationnumber 				= node.selectSingleNode("STN").getText(); // get data from the XML nodes and assign it to a variable
	            this.date 						= node.selectSingleNode("DATE").getText();
	            this.time 						= node.selectSingleNode("TIME").getText();
	            this.temperature 				= node.selectSingleNode("TEMP").getText();
	            this.dewpoint 					= node.selectSingleNode("DEWP").getText();
	            this.airpresurestationlevel 	= node.selectSingleNode("STP").getText();
	            this.airpresuresealevel 		= node.selectSingleNode("SLP").getText();
	            this.visability 				= node.selectSingleNode("VISIB").getText();
	            this.windspeed 					= node.selectSingleNode("WDSP").getText();
	            this.perception 				= node.selectSingleNode("PRCP").getText();
	            this.snowfallen 				= node.selectSingleNode("SNDP").getText();
	            this.specialcircumstances 		= node.selectSingleNode("FRSHTT").getText();
	            this.cloudiness 				= node.selectSingleNode("CLDC").getText();
	            this.winddirection 				= node.selectSingleNode("WNDDIR").getText();
	            
	            /*
	             * Gets the stationnumber from the Xml form and checks if there is a stationBuffer object created for it
	             * if that is not the case it creates the stationbuffer.
	             */
	            if (stationBufferMap.getmap().get(this.stationnumber) == null) { //gets the value for an id)
	            		stationBufferMap.getmap().put(this.stationnumber, new StationBuffer(this.stationnumber)); //no StationBuffer assigned, creating a new StationBuffer
	            		System.out.println("created a new StationBuffer for: station " + this.stationnumber + ".");
				    } // end of if
	            
	            //printParsedData(); // prints the parsed data to the console.
	            
	            ((StationBuffer) stationBufferMap.getmap().get(this.stationnumber)).printID(); // prints the station ID to the console
	            
	             // adds the parsed data to an arraylist in the instance of stationbuffer. 
	            ((StationBuffer) stationBufferMap.getmap().get(this.stationnumber)).addDataArrayToQueue(this.stationnumber, this.date, this.time, this.temperature, this.dewpoint, this.airpresurestationlevel, this.airpresuresealevel, this.visability, this.windspeed, this.perception, this.snowfallen, this.specialcircumstances, this.cloudiness, this.winddirection);
	            
	            ((StationBuffer) stationBufferMap.getmap().get(this.stationnumber)).printqueue();// prints the the size of the arraylist(queue buffer) to the console
	            
	            ((StationBuffer) stationBufferMap.getmap().get(this.stationnumber)).correctTemperature(); // corrects the temperature
	            
	            //((StationBuffer) stationBufferMap.getmap().get(this.stationnumber)).sendArray(); //depricated.

	            // adds the oldest arraylist in the queue/buffer to the send queue waiting to be sent to the vm.
	            ((StationBuffer) stationBufferMap.getmap().get(this.stationnumber)).addToSendQueue(this.stationBufferMap);
	         }
	      } catch (DocumentException e) {
	         System.out.println("Parsing failed : " + e);
	    	  e.printStackTrace();
	      }
	   }
	/*
	 * prints the parsed data from the XML forms to the console.
	 */
	public void printParsedData(){
        System.out.println("Station number : " + this.stationnumber);
        System.out.println("Date of measurement : " + this.date);
        System.out.println("Time of measurement : " + this.time);
        System.out.println("Temperature : " + this.temperature);
        System.out.println("Dewpoint : " + this.dewpoint);
        System.out.println("Air presure at station level : " + this.airpresurestationlevel);
        System.out.println("Air presure at sea level : " + this.airpresuresealevel);
        System.out.println("Visibility : " + this.visability);
        System.out.println("Wind speed : " + this.windspeed);
        System.out.println("Perception : " + this.perception);
        System.out.println("Snow fallen : " + this.snowfallen);
        System.out.println("Special Circumstances : " + this.specialcircumstances);
        System.out.println("Cloudiness : " + this.cloudiness);
        System.out.println("Wind direction : " + this.winddirection);
	}
}
